<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>JuStArt</title>
    <meta name="author" content="Juul de Rooij">
    <link rel="stylesheet" type="text/css" href="style.css">
</head>

<body lang="nl">

<div id="site">

    <div class="headerLeft">
        <img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/>
        <img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/>
        <div id="text"></div><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/>
        <img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/>
        <img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/>
        <img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/>
        <img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/>
        <img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/>
        <img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/>
    </div>
    <div class="headerRight">

        <img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/> <img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/> <img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/> <img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/> <img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/> <img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/> <img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/> <img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/> <img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/>

        <div id="numpad">

        <div class="numpadGrid">
            <div class="hoeWerken">
                <p style="padding-left: 2%;font-size: 9px;margin-top: 0%;text-align: left;">numlock</p>
                <p>Hoe Werken wij?</p>
            </div>
            <div class="minus">
                <p>-</p>
            </div>
            <div class="home">
                <p style="padding-left: 2%;font-size: 9px;margin-top: 0%;text-align: left;">7</p>
                <p>Home</p>
            </div>
            <div class="acht">
                <p style="padding-left: 2%;font-size: 9px;margin-top: 0%;text-align: left;">8</p>
            </div>
            <div class="negen">
                <p style="padding-left: 2%;font-size: 9px;margin-top: 0%;text-align: left;">9</p>
            </div>
            <div class="wieWijZijn">
                <p style="padding-left: 2%;font-size: 9px;margin-top: 0%;text-align: left;">+</p>
                <p style="padding-top: 15%;">wie</p>
                <p>zijn</p>
                <p>wij?</p>
            </div>
            <div class="iMouse">
                <img src="images/imuis.png">
            </div>
            <div class="vijf">
                <p style="padding-left: 2%;font-size: 9px;margin-top: 0%;text-align: left;">5</p>
            </div>
            <div class="vier">
                <p style="padding-left: 2%;font-size: 9px;margin-top: 0%;text-align: left;">6</p>
            </div>
            <div class="ideologieHeader">
                <p style="padding-left: 2%;font-size: 9px;margin-top: 0%;text-align: left;">3</p>
                <p>ideologie</p>
            </div>
            <div class="linked">
                <img src="images/linkedin.png">
            </div>
            <div class="enter">
                <p style="padding-left: 2%;font-size: 9px;margin-top: 0%;text-align: left;">enter</p>
            </div>
            <div class="contactHeader">
                <p style="padding-left: 2%;font-size: 9px;margin-top: 0%;text-align: left;">3</p>
                <p>contact</p>
            </div>
        </div>

        </div>

        <img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/> <img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/> <img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/> <img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/> <img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/> <img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/> <img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/> <img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/> <img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/>
        <img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/> <img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/> <img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/> <img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/> <img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/> <img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/>

    </div>
    <div class="lijnrechts">
        <img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/><img src='images/grijzester.png' onmouseover="this.src='images/gelester.png';" onmouseout="this.src='images/grijzester.png';"/>
    </div>

</div>